version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - run: npm install --production
      - run: npm test -- --ci --runInBand
      - run:
          name: set git name and email
          command: |
            git config --global user.email "arjungupta2110@gmail.com"
            git config --global user.name "Arjun"
      - run: npm run deploy

# test
# make sure it only deploys on master
