version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - run: npm install --production
      # - run: git config --global user.email "arjungupta2110@gmail.com"
      # - run: git config --global user.name "Arjun"
      - run: npm run deploy
