version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.3

    working_directory: ~/tic-tac-toe

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: npm install
      - run:
          name: tests
          command: ./.circleci/test
      - run:
          name: deploy if on master branch
          command: ./.circleci/deploy
