#! /usr/bin/env bash

if [ "${CIRCLE_BRANCH}" == "master" ]
then
  git config --global user.email "arjungupta2110@gmail.com";
  git config --global user.name "Arjun";
  npm run deploy
else
    echo "SKIP THIS BRANCH";
fi
